name: Build

on:
  push:
    branches:
    - linux-build # for testing
  
  workflow_dispatch:

env:
  BUILD_NAME: web_export
  GODOT_VERSION_STATUS: stable
  CCACHE_DIR: ${{ github.workspace }}/.ccache

jobs:
  build-ubuntu-editor:
    runs-on: ubuntu-22.04

    env:
      SCONS_FLAGS: >-
        module_mono_enabled=yes
        optimize=speed
        lto=full
        use_cache=yes
        platform=linuxbsd
        target=editor
        production=yes

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}
          submodules: recursive

      - name: Set Up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - name: Set Up SCons
        run: pip install scons

      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libx11-dev libxcursor-dev \
            libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev \
            libdbus-1-dev libudev-dev libxi-dev libxrandr-dev ccache

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.ccache
          key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/SCSub', '**/config.py') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.job }}-
            ${{ runner.os }}-
      
      - name: Build Editor (Linux)
        run: |
          mkdir -p ${{ github.workspace }}/.ccache
          scons -C godot ${{ env.SCONS_FLAGS }}
        env:
          CCACHE_DIR: ${{ github.workspace }}/.ccache

      - name: Debug Cache
        run: |
          ccache -s
          ls -R ${{ github.workspace }}/.ccache

      - name: Generate Mono Glue
        run: ./godot/bin/godot.linuxbsd.editor.x86_64.mono --headless --quit --generate-mono-glue godot/bin/glue

      - name: Save Version Text File
        run: |
          ./godot/bin/godot.linuxbsd.editor.x86_64.mono --headless --quit --version > godot/bin/version.txt
          cat godot/bin/version.txt

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: godot.linuxbsd.mono.${{ env.BUILD_NAME }}.editor
          path: |
            godot/bin/godot.linuxbsd*
            godot/bin/version.txt
            godot/bin/glue/**


  build-export-template-release:
    runs-on: ubuntu-22.04

    needs: build-ubuntu-editor

    env:
      SCONS_FLAGS: >-
        module_mono_enabled=yes
        optimize=speed
        lto=full
        use_cache=yes
        platform=web
        target=template_release
        ccflags="-DNDEBUG"
        linkflags="-sMALLOC=mimalloc"
        use_closure_compiler=yes

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}
          submodules: recursive

      - name: Set Up Dependencies
        uses: ./.github/actions/web-template-deps

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.ccache
          key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/SCSub', '**/config.py') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.job }}-
      
      - name: Build Web Template (Release)
        run: scons -C godot ${{ env.SCONS_FLAGS }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: godot.linuxbsd.mono.${{ env.BUILD_NAME }}.template_release
          path: |
            godot/bin/godot.web.template_release.wasm32.mono.zip
            godot/bin/GodotSharp/**
            godot/bin/nuget/**


  build-export-template-debug:
    runs-on: ubuntu-22.04

    needs: build-ubuntu-editor

    env:
      # Different build settings due to memory limitations of the standard github runner
      SCONS_FLAGS: >-
        module_mono_enabled=yes
        optimize=speed
        lto=thin
        use_cache=yes
        platform=web
        target=template_debug
        ccflags="-DNDEBUG"
        linkflags="-sMALLOC=mimalloc"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}
          submodules: recursive

      - name: Set Up Dependencies
        uses: ./.github/actions/web-template-deps

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.ccache
          key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/SCSub', '**/config.py') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.job }}-

      - name: Build Web Template (Debug)
        run: scons -C godot ${{ env.SCONS_FLAGS }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: godot.linuxbsd.mono.${{ env.BUILD_NAME }}.template_debug 
          path: godot/bin/godot.web.template_debug.wasm32.mono.zip


  build-final-zip:
    runs-on: ubuntu-22.04

    needs: [build-ubuntu-editor, build-export-template-release, build-export-template-debug]

    outputs:
      version: ${{ steps.prepare.outputs.version }}
      status: ${{ steps.prepare.outputs.status }}
      build_name: ${{ steps.prepare.outputs.build_name }}
      hash: ${{ steps.prepare.outputs.hash }}
      filename: ${{ steps.prepare.outputs.filename }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}

      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          path: godot/bin
          merge-multiple: true

      - name: Prepare Files
        id: prepare
        run: |
          # Get the version data from the app (previously saved to a file)
          # Remove the trailing newline
          version_output=$(tr -d '\r\n' < godot/bin/version.txt)

          # Regex matching: split the initial numerical/dot characters
          [[ $version_output =~ ^([0-9.]+)\.([^0-9.][^.]*)\.(mono\.)?(.+)\.([^.]+) ]]
          version=${BASH_REMATCH[1]}
          status=${BASH_REMATCH[2]}
          mono=${BASH_REMATCH[3]}
          build_name=${BASH_REMATCH[4]}
          hash=${BASH_REMATCH[5]}

          # Get a filename matching official Godot releases, e.g.: Godot_v4.6.1-stable_mono_web_export_win64
          filename=Godot_v${version}-${status}_${mono//./_}${build_name//./_}_linux_x86_64

          # Move the files to a folder
          mkdir $filename
          mv godot/bin/godot.linuxbsd.editor.x86_64.mono ${filename}/${filename}.x86_64
          mv godot/bin/GodotSharp $filename
          mv godot/bin/nuget $filename
          mv godot/bin/godot.web.template_release.wasm32.mono.zip ${filename}/web_release.zip
          mv godot/bin/godot.web.template_debug.wasm32.mono.zip ${filename}/web_debug.zip

          for extra_file in Program.cs global.json README.md; do
            if [ -f "$extra_file" ]; then
              mv "$extra_file" "$filename/"
            else
              echo "Note: $extra_file not found, skipping."
            fi
          done

          # Save the output for use in other steps
          echo "version=${version}" >> "$GITHUB_OUTPUT"
          echo "status=${status}" >> "$GITHUB_OUTPUT"
          echo "build_name=${build_name}" >> "$GITHUB_OUTPUT"
          echo "hash=${hash}" >> "$GITHUB_OUTPUT"
          echo "filename=${filename}" >> "$GITHUB_OUTPUT"

      - name: Create Install Shell Script
        run: |
          sh_filename=${{ steps.prepare.outputs.filename }}/install.sh
          cat > $sh_filename << 'EOF'
          #!/bin/bash
          set -e
          echo "Installing web export templates for Linux..."

          TEMPLATE_FOLDER="$HOME/.local/share/godot/export_templates/${{ steps.prepare.outputs.version }}.${{ steps.prepare.outputs.status }}.mono"
          NUGET_FOLDER="$HOME/.nuget/nuget"

          mkdir -p "$TEMPLATE_FOLDER"
          cp "web_release.zip" "$TEMPLATE_FOLDER/"
          cp "web_debug.zip" "$TEMPLATE_FOLDER/"

          echo "Setting up NuGet source..."
          mkdir -p "$NUGET_FOLDER"
          cp -r "nuget/." "$NUGET_FOLDER/"
          dotnet nuget add source "$NUGET_FOLDER" --name GodotLocalSource || true

          echo "Setting up WASM tools..."
          [ -f global.json ] && mv global.json global.json.disabled
          dotnet workload install wasm-tools
          [ -f global.json.disabled ] && mv global.json.disabled global.json

          chmod +x "./${{ steps.prepare.outputs.filename }}.x86_64"
          echo "Installation complete."
          EOF
          chmod +x $sh_filename
      
      - name: Install 7zip
        run: sudo apt-get install -y p7zip-full
      
      - name: Create Zip File
        run: 7z a ${{ steps.prepare.outputs.filename }}.zip ${{ steps.prepare.outputs.filename }} -r -mm=Deflate64 -mx=9 -bb

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.prepare.outputs.filename }}.artifact
          path: ${{ steps.prepare.outputs.filename }}.zip


  upload-release:
    runs-on: ubuntu-22.04

    needs: build-final-zip

    steps:
      - name: Download Artifact Zip File
        uses: actions/download-artifact@v8
        with:
          name: ${{ needs.build-final-zip.outputs.filename }}.artifact

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ needs.build-final-zip.outputs.filename }}.zip
          tag_name: ${{ needs.build-final-zip.outputs.version }}-${{ needs.build-final-zip.outputs.status }}
          target_commitish: ${{ github.ref }}
          prerelease: ${{ needs.build-final-zip.outputs.status != 'stable' }}
          body: >-
            Linux build of [Godot Engine](https://godotengine.org/)
            ${{ needs.build-final-zip.outputs.version }}-${{ needs.build-final-zip.outputs.status }}
            with experimental support for exporting C# projects to the web.


            How to use:

            1. Extract the zip file.

            2. Run the included `install.sh`.

            3. Change your Godot project's `.csproj` `TargetFramework` to `net9.0`, i.e., `<TargetFramework>net9.0</TargetFramework>`.

            4. Copy the included `Program.cs` to your project root if it doesn't have one.

            5. Open your project with the included app to export to the web.

            > <sub>If you are using self-contained mode, copy the web export templates to
            `editor_data\export_templates\${{ needs.build-final-zip.outputs.version }}.${{ needs.build-final-zip.outputs.status }}.mono`.</sub>


            **⚠️WARNING

            Games exported for the web do not support all features.

            See the main README for more information.**